---
title: "Assignment 2"
author: "Ted Ladas - s2124289"
output: html_document
---

```{r setup, include=FALSE}
require(kdensity)
require(stats)
knitr::opts_chunk$set(echo = FALSE)
```

```{r huperparameters}
# Requirements and hyperparameters:

set.seed(1903)
n_small = 200
n_large = 1e6
U_small = runif(n_small)
U_large = runif(n_large)

hyp_bins_small  = 20
hyp_bins_large  = 30
hyp_norm_mean   = 0
hyp_norm_sd     = 1
hyp_gamma_shape = 5
hyp_gamma_rate  = 1
hyp_mixing      = 0.5
hyp_ban         = 'nrd0'
```

```{r helper functions}
set.seed(1903)
set_kde = function(data,data_den,length,x_start,x_end,bins,
                    hyp_mean=hyp_norm_mean,
                    hyp_sd=hyp_norm_sd,
                    hyp_shape=hyp_gamma_shape,
                    hyp_rate=hyp_gamma_rate,
                    mixing = hyp_mixing){
  ## This function optimizes the kernel bandwidth for the KDE by a minimizing 
  ## the euclidean distance on a grid of given values. In can be further 
  ## enchanted easily, but this is a basic first prototype.
  h_seq = seq(1e-5, 10, by=0.1)
  dist_matrix = as.vector(matrix(1,nrow=length(h_seq)))
  x_in = seq(x_start, x_end, length.out=length)
  
  if(data_den=='norm')      {y_out = dnorm(x_in, mean=hyp_mean, sd=hyp_sd)}
  else if(data_den=='gamma'){y_out = dgamma(x_in, shape=hyp_shape, rate=hyp_rate)}
  else                      {y_out = mixing*dnorm (x_in, mean=hyp_mean, sd=hyp_sd) + 
                                      (1-mixing)*dgamma(x_in, shape=hyp_shape, rate=hyp_rate)}
  
  for(i in 1:length(h_seq)){
    kde_den=density(data,bw=h_seq[i],kernel='gaussian',n=bins)
    #dist_matrix[i]=sqrt(sum((kde_den$y-y_out)^2))
    dist_matrix[i]=sqrt(mean(outer(kde_den$y,y_out,"-")^2))
  }
  hyp_ban_opt = h_seq[which.min(dist_matrix)]
  kde_den=density(data,bw=hyp_ban_opt,kernel='gaussian',n=bins)
  
  # check whether the default bandwidth is better
  
  kde_den_default=density(data,bw='nrd0',kernel='gaussian',n=bins)
  gs_error = sqrt(mean(outer(kde_den$y,y_out,"-")^2)) # grid search min error
  df_error = sqrt(mean(outer(kde_den_default$y,y_out,"-")^2)) #default terror
  
  if(TRUE){ # the algorithm doesn't work yet 100% so this is why this locking mechanism exists for now
    cat('Switching to default parameters for KDE')
    kde_den = density(data,bw='nrd0',kernel='gaussian',n=bins)
  }
  return(kde_den)
}
```

```{r KDE vs Histogram}
set.seed(1903)
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Generate the unimodal data
y_small_uni_normal  = rnorm (n_small,
                            mean=hyp_norm_mean,
                            sd=hyp_norm_sd)
y_small_uni_gamma   = rgamma(n_small,
                            shape=hyp_gamma_shape,
                            rate=hyp_gamma_rate)
y_large_uni_normal  = rnorm (n_large,
                            mean=hyp_norm_mean,
                            sd=hyp_norm_sd)
y_large_uni_gamma   = rgamma(n_large,
                            shape=hyp_gamma_shape,
                            rate=hyp_gamma_rate)

# Generate the multimodal data
y_small_multi_norm_gamma = rep(NA, n_small)
y_large_multi_norm_gamma = rep(NA, n_large)

for(i in 1:n_small){
  if(U_small[i]<hyp_mixing){y_small_multi_norm_gamma[i] = rnorm (1,mean=hyp_norm_mean,sd=hyp_norm_sd)}
  else                     {y_small_multi_norm_gamma[i] = rgamma(1,shape=hyp_gamma_shape,rate=hyp_gamma_rate)}
}

for(i in 1:n_large){
  if(U_large[i]<hyp_mixing){y_large_multi_norm_gamma[i] = rnorm (1,mean=hyp_norm_mean,sd=hyp_norm_sd)}
  else                     {y_large_multi_norm_gamma[i] = rgamma(1,shape=hyp_gamma_shape,rate=hyp_gamma_rate)}
}


# Histograms and KDE
# KDEs
kde_small_uni_normal        = set_kde(data=y_small_uni_normal,data_den='norm',bins=hyp_bins_small,
                                      length=n_small,
                                      x_start=-5,
                                      x_end=5)

kde_small_uni_gamma         = set_kde(data=y_small_uni_gamma,data_den='gamma',bins=hyp_bins_small,
                                      length=n_small,
                                      x_start=-2,
                                      x_end=15)

kde_small_multi_norm_gamma  = set_kde(data=y_small_multi_norm_gamma,data_den='normgamma',bins=hyp_bins_small,
                                      length=n_small,
                                      x_start=-5,
                                      x_end=15)


kde_large_uni_normal        = set_kde(data=y_large_uni_normal,data_den='norm',bins=hyp_bins_large,
                                      length=n_large,
                                      x_start=-5,
                                      x_end=5)

kde_large_uni_gamma         = set_kde(data=y_large_uni_gamma,data_den='gamma',bins=hyp_bins_large,
                                      length=n_large,
                                      x_start=-2,
                                      x_end=15)

kde_large_multi_norm_gamma  = set_kde(data=y_large_multi_norm_gamma,data_den='normgamma',bins=hyp_bins_large,
                                      length=n_large,
                                      x_start=-4,
                                      x_end=15)

scaler=0.6
jpeg("./images/hist_vs_GKDE.jpg", width=4096*scaler, height=2160*scaler)
par(mfrow=c(2,3))
font = 2.2
x = seq(-5, 5, length.out=n_small)
y = dnorm(x, mean=hyp_norm_mean, sd=hyp_norm_sd)
hist(y_small_uni_normal,
     col='skyblue3',
     breaks=hyp_bins_small,
     freq= FALSE,
     main = 'Small Normal',
     xlab='Index',
     xlim=c(-5,5),
     ylim=c(0,0.5),
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
lines(kde_small_uni_normal,
      lwd=2,
      col='chocolate1')
lines(x,y,
      lwd=2)
rug(y_small_uni_normal)

x = seq(-2, 15, length.out=n_small)
y = dgamma(x, shape=hyp_gamma_shape, rate=hyp_gamma_rate)
hist(y_small_uni_gamma,
     col='skyblue3',
     breaks=hyp_bins_small,
     freq= FALSE,
     main = 'Small Gamma',
     xlab='Index',
     xlim=c(-2,15),
     ylim=c(0,0.3),
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
lines(kde_small_uni_gamma,
      lwd=2,
      col='chocolate1')
lines(x,y,
      lwd=2)
rug(y_small_uni_gamma)

x = seq(-5, 15, length.out=n_small)
y =  hyp_mixing      *dnorm (x, mean=hyp_norm_mean   , sd=hyp_norm_sd     ) +
      (1- hyp_mixing )*dgamma(x, shape=hyp_gamma_shape, rate=hyp_gamma_rate)
hist(y_small_multi_norm_gamma,
     col='skyblue3',
     breaks=hyp_bins_small,
     freq= FALSE,
     main = 'Small Normal-Gamma',
     xlab='Index',
     xlim=c(-5,15),
     ylim=c(0,0.2),
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
lines(kde_small_multi_norm_gamma,
      lwd=2,
      col='chocolate1')
lines(x,y,
     lwd=2)
legend("topright",
       c("Gaussian Kernel", "Histogram", "True Distribution"),
       col=c("chocolate1", "skyblue3","black"),
       lwd=10,
       cex=font)
rug(y_small_multi_norm_gamma)

#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

x = seq(-5, 5, length.out=n_large)
y = dnorm(x, mean=hyp_norm_mean, sd=hyp_norm_sd)
hist(y_large_uni_normal,
     col='darkolivegreen',
     breaks=hyp_bins_large,
     freq= FALSE,
     main = 'Large Normal',
     xlab='Index',
     xlim=c(-5,5),
     ylim=c(0,0.5),
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
lines(kde_large_uni_normal,
      lwd=2,
      col='deeppink')
lines(x,y,
      lwd=2)

x = seq(-2, 15, length.out=n_large)
y = dgamma(x, shape=hyp_gamma_shape, rate=hyp_gamma_rate)
hist(y_large_uni_gamma,
     col='darkolivegreen',
     breaks=hyp_bins_large,
     freq= FALSE,
     main = 'Large Gamma',
     xlab='Index',
     xlim=c(-2,15),
     ylim=c(0,0.3),
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
lines(kde_large_uni_gamma,
      lwd=2,
      col='deeppink')
lines(x,y,
      lwd=2)

x = seq(-4, 15, length.out=n_large)
y =  hyp_mixing      *dnorm (x, mean=hyp_norm_mean   , sd=hyp_norm_sd     ) +
      (1- hyp_mixing )*dgamma(x, shape=hyp_gamma_shape, rate=hyp_gamma_rate)
hist(y_large_multi_norm_gamma,
     col='darkolivegreen',
     breaks=hyp_bins_large,
     freq= FALSE,
     main = 'Large Normal-Gamma',
     xlab='Index',
     xlim=c(-4,15),
     ylim=c(0,0.3),
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
lines(kde_large_multi_norm_gamma,
      lwd=2,
      col='deeppink')
lines(x,y,
      lwd=2)
legend("topright",
       c("Gaussian Kernel", "Histogram", "True Distribution"),
       col=c("deeppink", "darkolivegreen","black"),
       lwd=10,
       cex=font)


dev.off()
par(mfrow=c(1,1))

cat("\n###Script executed successfully!###")
```

```{r MCMC}
set.seed(1903)
n               = seq(100,2e3, by=50)
R               = 1000
hyp_mixing      = 0.5
hyp_norm_mean   = 0
hyp_norm_sd     = 1
hyp_gamma_shape = 5
hyp_gamma_rate  = 1
results = matrix(NA, length(n), 3)

for(i in 1:length(n)){
  y_uni_normal         = matrix(NA, R, n[i]) 
  y_uni_gamma          = matrix(NA, R, n[i]) 
  y_multi_normal_gamma_0 = matrix(NA, R, n[i]/2)
  y_multi_normal_gamma_1 = matrix(NA, R, n[i]/2) 
  y_multi_normal_gamma = matrix(NA, R, n[i]) 
  # MCMC
  for(r in 1:R){
    y_uni_normal[r, ] = rnorm (n[i],mean=hyp_norm_mean,sd=hyp_norm_sd)
    y_uni_gamma[r, ]  = rgamma(n[i],shape=hyp_gamma_shape,rate=hyp_gamma_rate)
    y_multi_normal_gamma_0[r, ] = rnorm (n[i]/2,mean=hyp_norm_mean,sd=hyp_norm_sd)
    y_multi_normal_gamma_1[r, ] = rgamma(n[i]/2,shape=hyp_gamma_shape,rate=hyp_gamma_rate)
  }
  y_multi_normal_gamma    = cbind(y_multi_normal_gamma_0,y_multi_normal_gamma_1)
  MCMC_uni_normal         = colMeans(y_uni_normal) 
  MCMC_uni_gamma          = colMeans(y_uni_gamma) 
  MCMC_multi_normal_gamma = colMeans(y_multi_normal_gamma) 
  # h_normal       = bw.ucv(MCMC_uni_normal)
  # h_gamma        = bw.ucv(MCMC_uni_gamma)
  # h_normal_gamma = bw.ucv(MCMC_multi_normal_gamma)
  
  MCMC_kde_uni_normal         = density(MCMC_uni_normal,
                                        n=n[i],
                                        bw='nrd0')
  MCMC_kde_uni_gamma          = density(MCMC_uni_gamma,
                                        n=n[i],
                                        bw='nrd0')
  MCMC_kde_multi_normal_gamma = density(MCMC_multi_normal_gamma,
                                        n=n[i],
                                        bw='nrd0')
  
  # https://stats.stackexchange.com/questions/390777/how-to-compute-integrated-squared-error-for-kernel-density-estimation-in-r
  MCMC_uni_normal_error         = splinefun(MCMC_kde_uni_normal$x,
                                            (MCMC_kde_uni_normal$y-dnorm(MCMC_kde_uni_normal$x))^2)
  ISE_uni_normal                = integrate(MCMC_uni_normal_error,
                                            lower=min(MCMC_uni_normal),
                                            upper=max(MCMC_uni_normal))
  
  MCMC_uni_gamma_error          = splinefun(MCMC_kde_uni_gamma$x,
                                            (MCMC_kde_uni_gamma$y-dnorm(MCMC_kde_uni_gamma$x))^2)
  ISE_uni_gamma                 = integrate(MCMC_uni_gamma_error,
                                            lower=min(MCMC_uni_gamma),
                                            upper=max(MCMC_uni_gamma))
  
  MCMC_multi_normal_gamma_error = splinefun(MCMC_kde_multi_normal_gamma$x,
                                            (MCMC_kde_multi_normal_gamma$y-dnorm(MCMC_kde_multi_normal_gamma$x))^2)
  ISE_multi_normal_gamma        = integrate(MCMC_multi_normal_gamma_error,
                                            lower=min(MCMC_multi_normal_gamma),
                                            upper=max(MCMC_multi_normal_gamma))
  
  results[i,1] = ISE_uni_normal$value
  results[i,2] = ISE_uni_gamma$value
  results[i,3] = ISE_multi_normal_gamma$value
}

resutl_normal_250       = results[4,1]
resutl_normal_500       = results[9,1]
resutl_normal_1e3       = results[19,1]
resutl_gamma_250        = results[4,2]
resutl_gamma_500        = results[9,2]
resutl_gamma_1e3        = results[19,2]
resutl_normal_gamma_250 = results[4,3]
resutl_normal_gamma_500 = results[9,3]
resutl_normal_gamma_1e3 = results[19,3]

scaler=0.3
font=1.2
jpeg("./images/MISE error.jpg", width=4096*scaler, height=2160*scaler)
par(mfrow=c(3.5,1), mai=c(0.3,0.3,0.5,0.5))
plot(n,
     results[,1],
     main='MISE Normal model',
     ylab='MISE',
     xlab=expression('n'),
     ylim=c(7.2, 8.9),
     type='b',
     lwd=2,
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
abline(v=250, col='red4', lwd=2.5)
abline(v=500, col='green4', lwd=2.5)
abline(v=1000, col='blue4', lwd=2.5)
text(x=250,
     y=resutl_normal_250,
     c(round(resutl_normal_250,2)),
     adj = c(0,0),
     cex=2)
text(x=500,
     y=resutl_normal_500,
     c(round(resutl_normal_1e3,2)),
     adj = c(0,0),
     cex=2)
text(x=1000,
     y=resutl_normal_1e3,
     c(round(resutl_normal_1e3,2)),
     pos=2,
     cex=2)

plot(n,
     results[,2],
     main='MISE Gamma model',
     ylab='MISE',
     xlab=expression('n'),
     ylim=c(3.4, 4.2),
     type='b',
     lwd=2,
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
abline(v=250, col='red4', lwd=2.5)
abline(v=500, col='green4', lwd=2.5)
abline(v=1000, col='blue4', lwd=2.5)
text(x=250,
     y=resutl_gamma_250,
     c(round(resutl_gamma_250,2)),
     pos=4,
     cex=2)
text(x=500,
     y=resutl_gamma_500,
     c(round(resutl_gamma_1e3,2)),
     adj = c(0,0),
     cex=2)
text(x=1000,
     y=resutl_gamma_1e3,
     c(round(resutl_gamma_1e3,2)),
     pos=2,
     cex=2)

plot(n,
     results[,3],
     main='MISE Normal-Gamma model',
     ylab='MISE',
     xlab=expression('n'),
     ylim=c(0, 0.18),
     type='b',
     lwd=2,
     cex.lab=font,
     cex.axis=font,
     cex.main=font,
     cex.sub=font)
abline(v=250, col='red4', lwd=2.5)
abline(v=500, col='green4', lwd=2.5)
abline(v=1000, col='blue4', lwd=2.5)
text(x=250,
     y=resutl_normal_gamma_250,
     c(round(resutl_normal_gamma_250,2)),
     adj = c(0,1),
     cex=2)
text(x=500,
     y=resutl_normal_gamma_500,
     c(round(resutl_normal_gamma_1e3,2)),
     adj = c(0,1),
     cex=2)
text(x=1000,
     y=resutl_normal_gamma_1e3,
     c(round(resutl_normal_gamma_1e3,2)),
     adj = c(0,1),
     cex=2)
dev.off()

cat("\n###Script executed successfully!###")

```




```{r stackoverflow code}
set.seed(1)
x1 = rnorm(250) 
#Computing of bandwidth
h1 = bw.ucv(x1)
#Estimate
est = density(x1,kernel = "gaussian",bw = h1)

# Create approx func obj and integrate()
splxy = splinefun(est$x, (est$y - dnorm(est$x))^2)
integrate(splxy, lower = min(x1), upper = max(x1)) # res 0.0006681713


plot(1:10, 1:10, main = "text(...) examples\n~~~~~~~~~~~~~~")
points(c(6,2), c(2,1), pch = 3, cex = 4, col = "red")
text(6, 2, "the text is CENTERED around (x,y) = (6,2) by default",
     cex = .8)
text(2, 1, "or Left/Bottom - JUSTIFIED at (2,1) by 'adj = c(0,0)'",
     adj = c(0,0))
text(4, 9, expression(hat(beta) == (X^t * X)^{-1} * X^t * y))
text(4, 8.4, "expression(hat(beta) == (X^t * X)^{-1} * X^t * y)",
     cex = .75)
text(4, 7, expression(bar(x) == sum(frac(x[i], n), i==1, n)))
```